### ISSUE TITLE
Provide a RESTful API

### ISSUE THREAD

**Issue by dilyantraykov** [AmphitriteTeam/telerickr#2]
The endpoints should provide CRUD operations: POST, GET, PUT and DELETE

**Comment by mr-krustev** [comment]
petyodelta implemented:

## AlbumsController
- Get()
- Get(int id)
- Post(AlbumRequestModel model)
- Delete(int id)

## PhotosController
- Get()
- Get(int id)
- Post(PhotoRequestModel model)

**Comment by mr-krustev** [comment]
mr.krustev implemented:

## AlbumsController
- Put(int id, AlbumRequestModel model)
- Deleting Album now will delete all relevant photos.

## PhotosController
- Put(int id, bool like)
- Delete(int id)

## CommentsController
- Get()
- Get(int id)
- Post(int photoId, CommentRequestModel comment)
- Put(int commentId, CommentRequestModel comment)
- Delete(int id)
