### ISSUE TITLE
Add Unit and/or integration tests

### ISSUE THREAD

**Issue by dilyantraykov** [AmphitriteTeam/telerickr#7]

**Comment by mr-krustev** [comment]
## Unit Tests

### Mockings
- Using the repository pattern - mocked class is InMemoryRepository< T >
- Controllers are mocked to have "this.user.Identity"

### AlbumsControllerTests
- Get - implemented
- Put - implemented
- Post - implemented
- Delete - implemented

### PhotosControllerTests
- Get - implemented
- Put - implemented
- Post - implemented
- Delete - implemented

### CommentsControllerTests
- Get - implemented
- Put - implemented
- Post - implemented
- Delete - implemented
